{% set dependency0 =  ref('model_15')  %}
{% set dependency1 =  ref('model_17')  %}
{% set dependency2 =  ref('model_10')  %}
{% set dependency3 =  ref('model_55')  %}
{% set dependency4 =  ref('model_47')  %}
{% set dependency5 =  ref('model_12')  %}
{% set dependency6 =  ref('model_31')  %}
{% set dependency7 =  ref('model_57')  %}
{% set dependency8 =  ref('model_19')  %}
{% set dependency9 =  ref('model_50')  %}
{% set dependency10 =  ref('model_16')  %}
{% set dependency11 =  ref('model_22')  %}
{% set dependency12 =  ref('model_9')  %}
{% set dependency13 =  ref('model_25')  %}
{% set dependency14 =  ref('model_54')  %}
{% set dependency15 =  ref('model_39')  %}
{% set dependency16 =  ref('model_35')  %}
{% set dependency17 =  ref('model_61')  %}
{% set dependency18 =  ref('model_40')  %}
{% set dependency19 =  ref('model_45')  %}
{% set dependency20 =  ref('model_18')  %}
{% set dependency21 =  ref('model_46')  %}
{% set dependency22 =  ref('model_7')  %}
{% set dependency23 =  ref('model_36')  %}
{% set dependency24 =  ref('model_8')  %}
{% set dependency25 =  ref('model_53')  %}
{% set dependency26 =  ref('model_34')  %}
{% set dependency27 =  ref('model_38')  %}
{% set dependency28 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency29 =  ref('model_20')  %}
{% set dependency30 =  ref('model_58')  %}
{% set dependency31 =  ref('model_24')  %}

SELECT * from dependency0
