{% set dependency0 =  ref('model_22')  %}
{% set dependency1 =  ref('model_56')  %}
{% set dependency2 =  ref('model_11')  %}
{% set dependency3 =  ref('model_33')  %}
{% set dependency4 =  ref('model_14')  %}
{% set dependency5 =  ref('model_24')  %}
{% set dependency6 =  source('aayan_test', 'example_table_2')  %}
{% set dependency7 =  ref('model_27')  %}
{% set dependency8 =  ref('model_71')  %}
{% set dependency9 =  ref('model_46')  %}
{% set dependency10 =  ref('model_82')  %}
{% set dependency11 =  ref('model_81')  %}
{% set dependency12 =  ref('model_68')  %}
{% set dependency13 =  ref('model_39')  %}
{% set dependency14 =  ref('model_64')  %}
{% set dependency15 =  ref('model_53')  %}
{% set dependency16 =  ref('model_13')  %}
{% set dependency17 =  ref('model_3')  %}
{% set dependency18 =  ref('model_74')  %}
{% set dependency19 =  ref('model_28')  %}
{% set dependency20 =  ref('model_63')  %}
{% set dependency21 =  ref('model_77')  %}
{% set dependency22 =  ref('model_51')  %}
{% set dependency23 =  source('aayan_test', 'example_table')  %}
{% set dependency24 =  ref('model_67')  %}
{% set dependency25 =  ref('model_42')  %}
{% set dependency26 =  ref('model_44')  %}
{% set dependency27 =  ref('model_58')  %}
{% set dependency28 =  ref('model_47')  %}
{% set dependency29 =  ref('model_15')  %}
{% set dependency30 =  ref('model_55')  %}
{% set dependency31 =  ref('model_4')  %}
{% set dependency32 =  ref('model_52')  %}
{% set dependency33 =  ref('model_40')  %}

SELECT * from dependency0
