{% set dependency0 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency1 =  ref('model_59')  %}
{% set dependency2 =  ref('model_8')  %}
{% set dependency3 =  ref('model_10')  %}
{% set dependency4 =  ref('model_58')  %}
{% set dependency5 =  ref('model_57')  %}
{% set dependency6 =  ref('model_62')  %}
{% set dependency7 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency8 =  ref('model_22')  %}
{% set dependency9 =  ref('model_75')  %}
{% set dependency10 =  ref('model_3')  %}
{% set dependency11 =  ref('model_20')  %}
{% set dependency12 =  ref('model_47')  %}
{% set dependency13 =  ref('model_45')  %}
{% set dependency14 =  ref('model_28')  %}
{% set dependency15 =  ref('model_26')  %}
{% set dependency16 =  ref('model_12')  %}
{% set dependency17 =  ref('model_11')  %}
{% set dependency18 =  source('aayan_test', 'example_table_2')  %}
{% set dependency19 =  ref('model_17')  %}
{% set dependency20 =  ref('model_34')  %}
{% set dependency21 =  ref('model_39')  %}
{% set dependency22 =  ref('model_51')  %}
{% set dependency23 =  ref('model_5')  %}
{% set dependency24 =  ref('model_6')  %}
{% set dependency25 =  source('aayan_test', 'example_table')  %}
{% set dependency26 =  ref('model_76')  %}
{% set dependency27 =  ref('model_78')  %}
{% set dependency28 =  ref('model_42')  %}
{% set dependency29 =  ref('model_41')  %}
{% set dependency30 =  ref('model_61')  %}
{% set dependency31 =  ref('model_52')  %}
{% set dependency32 =  ref('model_2')  %}
{% set dependency33 =  ref('model_13')  %}
{% set dependency34 =  ref('model_30')  %}
{% set dependency35 =  ref('model_9')  %}
{% set dependency36 =  ref('model_50')  %}
{% set dependency37 =  ref('model_60')  %}
{% set dependency38 =  ref('model_77')  %}
{% set dependency39 =  ref('model_15')  %}
{% set dependency40 =  ref('model_74')  %}
{% set dependency41 =  ref('model_80')  %}
{% set dependency42 =  ref('model_55')  %}
{% set dependency43 =  ref('model_73')  %}
{% set dependency44 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency45 =  ref('model_4')  %}
{% set dependency46 =  ref('model_27')  %}
{% set dependency47 =  ref('model_66')  %}
{% set dependency48 =  ref('model_14')  %}
{% set dependency49 =  ref('model_1')  %}
{% set dependency50 =  ref('model_33')  %}
{% set dependency51 =  ref('model_35')  %}
{% set dependency52 =  ref('model_63')  %}
{% set dependency53 =  ref('model_56')  %}
{% set dependency54 =  ref('model_37')  %}
{% set dependency55 =  ref('model_25')  %}
{% set dependency56 =  ref('model_7')  %}
{% set dependency57 =  ref('model_69')  %}
{% set dependency58 =  ref('model_24')  %}
{% set dependency59 =  ref('model_71')  %}

SELECT * from {{ dependency0 }}
