{% set dependency0 =  ref('model_8')  %}
{% set dependency1 =  ref('model_39')  %}
{% set dependency2 =  ref('model_18')  %}
{% set dependency3 =  ref('model_46')  %}
{% set dependency4 =  ref('model_35')  %}
{% set dependency5 =  ref('model_33')  %}
{% set dependency6 =  ref('model_10')  %}
{% set dependency7 =  ref('model_50')  %}
{% set dependency8 =  ref('model_15')  %}
{% set dependency9 =  ref('model_4')  %}
{% set dependency10 =  ref('model_26')  %}
{% set dependency11 =  ref('model_47')  %}
{% set dependency12 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency13 =  ref('model_19')  %}
{% set dependency14 =  ref('model_34')  %}
{% set dependency15 =  ref('model_32')  %}
{% set dependency16 =  ref('model_43')  %}
{% set dependency17 =  ref('model_40')  %}
{% set dependency18 =  ref('model_12')  %}
{% set dependency19 =  ref('model_49')  %}
{% set dependency20 =  ref('model_9')  %}
{% set dependency21 =  ref('model_2')  %}
{% set dependency22 =  ref('model_45')  %}
{% set dependency23 =  ref('model_25')  %}
{% set dependency24 =  ref('model_13')  %}
{% set dependency25 =  ref('model_29')  %}
{% set dependency26 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency27 =  ref('model_21')  %}
{% set dependency28 =  ref('model_24')  %}
{% set dependency29 =  ref('model_16')  %}

SELECT * from dependency0
