{% set dependency0 =  ref('model_37')  %}
{% set dependency1 =  ref('model_25')  %}
{% set dependency2 =  ref('model_53')  %}
{% set dependency3 =  ref('model_43')  %}
{% set dependency4 =  ref('model_83')  %}
{% set dependency5 =  ref('model_80')  %}
{% set dependency6 =  ref('model_16')  %}
{% set dependency7 =  ref('model_32')  %}
{% set dependency8 =  source('aayan_test', 'example_table_2')  %}
{% set dependency9 =  ref('model_20')  %}
{% set dependency10 =  ref('model_19')  %}
{% set dependency11 =  ref('model_46')  %}
{% set dependency12 =  ref('model_49')  %}
{% set dependency13 =  ref('model_38')  %}
{% set dependency14 =  ref('model_42')  %}
{% set dependency15 =  ref('model_45')  %}
{% set dependency16 =  ref('model_5')  %}
{% set dependency17 =  ref('model_65')  %}
{% set dependency18 =  ref('model_8')  %}
{% set dependency19 =  ref('model_24')  %}
{% set dependency20 =  ref('model_71')  %}
{% set dependency21 =  ref('model_11')  %}
{% set dependency22 =  ref('model_30')  %}
{% set dependency23 =  ref('model_35')  %}
{% set dependency24 =  ref('model_72')  %}
{% set dependency25 =  ref('model_50')  %}
{% set dependency26 =  ref('model_60')  %}
{% set dependency27 =  ref('model_23')  %}
{% set dependency28 =  ref('model_61')  %}
{% set dependency29 =  ref('model_58')  %}
{% set dependency30 =  ref('model_1')  %}
{% set dependency31 =  ref('model_56')  %}
{% set dependency32 =  ref('model_41')  %}
{% set dependency33 =  ref('model_40')  %}
{% set dependency34 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency35 =  ref('model_51')  %}
{% set dependency36 =  ref('model_27')  %}
{% set dependency37 =  ref('model_76')  %}
{% set dependency38 =  ref('model_64')  %}
{% set dependency39 =  ref('model_13')  %}
{% set dependency40 =  ref('model_47')  %}
{% set dependency41 =  ref('model_28')  %}
{% set dependency42 =  ref('model_12')  %}

SELECT * from dependency0
