{% set dependency0 =  ref('model_69')  %}
{% set dependency1 =  ref('model_67')  %}
{% set dependency2 =  ref('model_47')  %}
{% set dependency3 =  ref('model_42')  %}
{% set dependency4 =  ref('model_55')  %}
{% set dependency5 =  ref('model_39')  %}
{% set dependency6 =  ref('model_48')  %}
{% set dependency7 =  ref('model_25')  %}
{% set dependency8 =  ref('model_62')  %}
{% set dependency9 =  ref('model_2')  %}
{% set dependency10 =  ref('model_40')  %}
{% set dependency11 =  source('aayan_test', 'example_table')  %}
{% set dependency12 =  ref('model_17')  %}
{% set dependency13 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency14 =  ref('model_64')  %}
{% set dependency15 =  ref('model_30')  %}
{% set dependency16 =  ref('model_33')  %}
{% set dependency17 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency18 =  ref('model_31')  %}
{% set dependency19 =  ref('model_19')  %}
{% set dependency20 =  ref('model_10')  %}
{% set dependency21 =  ref('model_9')  %}
{% set dependency22 =  ref('model_46')  %}
{% set dependency23 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency24 =  ref('model_57')  %}
{% set dependency25 =  ref('model_5')  %}
{% set dependency26 =  ref('model_16')  %}
{% set dependency27 =  ref('model_61')  %}
{% set dependency28 =  ref('model_50')  %}

SELECT * from dependency0
