{% set dependency0 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency1 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency2 =  ref('model_13')  %}
{% set dependency3 =  ref('model_15')  %}
{% set dependency4 =  ref('model_17')  %}
{% set dependency5 =  ref('model_69')  %}
{% set dependency6 =  ref('model_52')  %}
{% set dependency7 =  ref('model_20')  %}
{% set dependency8 =  ref('model_68')  %}
{% set dependency9 =  ref('model_21')  %}
{% set dependency10 =  ref('model_66')  %}
{% set dependency11 =  ref('model_58')  %}
{% set dependency12 =  ref('model_42')  %}
{% set dependency13 =  ref('model_59')  %}
{% set dependency14 =  ref('model_23')  %}
{% set dependency15 =  ref('model_26')  %}
{% set dependency16 =  ref('model_29')  %}
{% set dependency17 =  ref('model_32')  %}
{% set dependency18 =  ref('model_60')  %}
{% set dependency19 =  ref('model_7')  %}
{% set dependency20 =  ref('model_22')  %}
{% set dependency21 =  ref('model_56')  %}
{% set dependency22 =  ref('model_50')  %}
{% set dependency23 =  ref('model_28')  %}
{% set dependency24 =  ref('model_47')  %}
{% set dependency25 =  ref('model_24')  %}
{% set dependency26 =  ref('model_33')  %}
{% set dependency27 =  ref('model_37')  %}
{% set dependency28 =  ref('model_34')  %}
{% set dependency29 =  ref('model_45')  %}
{% set dependency30 =  ref('model_27')  %}
{% set dependency31 =  ref('model_18')  %}
{% set dependency32 =  ref('model_70')  %}
{% set dependency33 =  ref('model_16')  %}
{% set dependency34 =  ref('model_2')  %}
{% set dependency35 =  ref('model_43')  %}
{% set dependency36 =  ref('model_25')  %}
{% set dependency37 =  ref('model_5')  %}

SELECT * from dependency0
