{% set dependency0 =  source('aayan_test', 'example_table_2')  %}
{% set dependency1 =  ref('model_28')  %}
{% set dependency2 =  ref('model_7')  %}
{% set dependency3 =  ref('model_38')  %}
{% set dependency4 =  ref('model_37')  %}
{% set dependency5 =  ref('model_26')  %}
{% set dependency6 =  ref('model_10')  %}
{% set dependency7 =  ref('model_13')  %}
{% set dependency8 =  ref('model_31')  %}
{% set dependency9 =  ref('model_2')  %}
{% set dependency10 =  ref('model_3')  %}
{% set dependency11 =  ref('model_5')  %}
{% set dependency12 =  ref('model_18')  %}
{% set dependency13 =  ref('model_9')  %}
{% set dependency14 =  ref('model_16')  %}
{% set dependency15 =  ref('model_39')  %}
{% set dependency16 =  ref('model_36')  %}
{% set dependency17 =  ref('model_6')  %}
{% set dependency18 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency19 =  source('aayan_test', 'example_table')  %}
{% set dependency20 =  ref('model_8')  %}
{% set dependency21 =  ref('model_17')  %}
{% set dependency22 =  ref('model_19')  %}
{% set dependency23 =  ref('model_30')  %}
{% set dependency24 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency25 =  ref('model_11')  %}
{% set dependency26 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency27 =  ref('model_20')  %}
{% set dependency28 =  ref('model_14')  %}
{% set dependency29 =  ref('model_33')  %}
{% set dependency30 =  ref('model_35')  %}
{% set dependency31 =  ref('model_27')  %}
{% set dependency32 =  ref('model_21')  %}
{% set dependency33 =  ref('model_40')  %}
{% set dependency34 =  ref('model_42')  %}

SELECT * from dependency0
