{% set dependency0 =  ref('model_76')  %}
{% set dependency1 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency2 =  ref('model_47')  %}
{% set dependency3 =  ref('model_25')  %}
{% set dependency4 =  ref('model_3')  %}
{% set dependency5 =  ref('model_18')  %}
{% set dependency6 =  ref('model_61')  %}
{% set dependency7 =  ref('model_64')  %}
{% set dependency8 =  ref('model_70')  %}
{% set dependency9 =  ref('model_53')  %}
{% set dependency10 =  ref('model_49')  %}
{% set dependency11 =  ref('model_29')  %}
{% set dependency12 =  ref('model_11')  %}
{% set dependency13 =  ref('model_37')  %}
{% set dependency14 =  ref('model_63')  %}
{% set dependency15 =  ref('model_40')  %}
{% set dependency16 =  ref('model_41')  %}
{% set dependency17 =  ref('model_34')  %}
{% set dependency18 =  ref('model_52')  %}
{% set dependency19 =  ref('model_30')  %}
{% set dependency20 =  ref('model_31')  %}
{% set dependency21 =  ref('model_62')  %}
{% set dependency22 =  ref('model_19')  %}
{% set dependency23 =  ref('model_35')  %}
{% set dependency24 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency25 =  ref('model_55')  %}
{% set dependency26 =  ref('model_26')  %}
{% set dependency27 =  ref('model_59')  %}
{% set dependency28 =  ref('model_48')  %}
{% set dependency29 =  ref('model_56')  %}
{% set dependency30 =  ref('model_21')  %}
{% set dependency31 =  ref('model_77')  %}
{% set dependency32 =  ref('model_68')  %}
{% set dependency33 =  ref('model_72')  %}
{% set dependency34 =  ref('model_74')  %}
{% set dependency35 =  ref('model_79')  %}
{% set dependency36 =  ref('model_16')  %}
{% set dependency37 =  ref('model_58')  %}
{% set dependency38 =  ref('model_6')  %}
{% set dependency39 =  ref('model_71')  %}
{% set dependency40 =  ref('model_24')  %}

SELECT * from dependency0
