{% set dependency0 =  ref('model_44')  %}
{% set dependency1 =  ref('model_7')  %}
{% set dependency2 =  ref('model_31')  %}
{% set dependency3 =  ref('model_13')  %}
{% set dependency4 =  ref('model_9')  %}
{% set dependency5 =  ref('model_36')  %}
{% set dependency6 =  ref('model_40')  %}
{% set dependency7 =  ref('model_30')  %}
{% set dependency8 =  ref('model_14')  %}
{% set dependency9 =  ref('model_56')  %}
{% set dependency10 =  ref('model_22')  %}
{% set dependency11 =  ref('model_20')  %}
{% set dependency12 =  ref('model_58')  %}
{% set dependency13 =  ref('model_51')  %}
{% set dependency14 =  ref('model_25')  %}
{% set dependency15 =  ref('model_53')  %}
{% set dependency16 =  ref('model_41')  %}
{% set dependency17 =  ref('model_4')  %}
{% set dependency18 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency19 =  ref('model_62')  %}
{% set dependency20 =  ref('model_57')  %}
{% set dependency21 =  ref('model_28')  %}
{% set dependency22 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency23 =  ref('model_3')  %}
{% set dependency24 =  ref('model_37')  %}
{% set dependency25 =  ref('model_11')  %}
{% set dependency26 =  ref('model_17')  %}
{% set dependency27 =  ref('model_2')  %}
{% set dependency28 =  ref('model_60')  %}
{% set dependency29 =  ref('model_61')  %}
{% set dependency30 =  ref('model_47')  %}
{% set dependency31 =  ref('model_21')  %}
{% set dependency32 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency33 =  source('aayan_test', 'example_table_2')  %}
{% set dependency34 =  ref('model_52')  %}

SELECT * from dependency0
