{% set dependency0 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency1 =  source('aayan_test', 'example_table')  %}
{% set dependency2 =  ref('model_47')  %}
{% set dependency3 =  ref('model_17')  %}
{% set dependency4 =  ref('model_33')  %}
{% set dependency5 =  ref('model_39')  %}
{% set dependency6 =  ref('model_55')  %}
{% set dependency7 =  ref('model_44')  %}
{% set dependency8 =  ref('model_19')  %}
{% set dependency9 =  ref('model_35')  %}
{% set dependency10 =  ref('model_12')  %}
{% set dependency11 =  ref('model_38')  %}
{% set dependency12 =  ref('model_18')  %}
{% set dependency13 =  ref('model_3')  %}
{% set dependency14 =  ref('model_51')  %}
{% set dependency15 =  ref('model_6')  %}
{% set dependency16 =  ref('model_34')  %}
{% set dependency17 =  ref('model_5')  %}
{% set dependency18 =  ref('model_8')  %}
{% set dependency19 =  ref('model_23')  %}
{% set dependency20 =  ref('model_36')  %}
{% set dependency21 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency22 =  ref('model_1')  %}
{% set dependency23 =  ref('model_15')  %}
{% set dependency24 =  ref('model_10')  %}
{% set dependency25 =  ref('model_16')  %}
{% set dependency26 =  ref('model_41')  %}
{% set dependency27 =  ref('model_42')  %}
{% set dependency28 =  ref('model_56')  %}
{% set dependency29 =  ref('model_40')  %}
{% set dependency30 =  ref('model_26')  %}
{% set dependency31 =  ref('model_32')  %}

SELECT * from {{ dependency0 }}
