{% set dependency0 =  ref('model_15')  %}
{% set dependency1 =  ref('model_89')  %}
{% set dependency2 =  ref('model_37')  %}
{% set dependency3 =  ref('model_57')  %}
{% set dependency4 =  ref('model_33')  %}
{% set dependency5 =  ref('model_19')  %}
{% set dependency6 =  ref('model_14')  %}
{% set dependency7 =  ref('model_80')  %}
{% set dependency8 =  source('aayan_test', 'example_table')  %}
{% set dependency9 =  ref('model_30')  %}
{% set dependency10 =  ref('model_62')  %}
{% set dependency11 =  ref('model_85')  %}
{% set dependency12 =  ref('model_16')  %}
{% set dependency13 =  ref('model_3')  %}
{% set dependency14 =  ref('model_74')  %}
{% set dependency15 =  ref('model_90')  %}
{% set dependency16 =  ref('model_4')  %}
{% set dependency17 =  ref('model_27')  %}
{% set dependency18 =  ref('model_87')  %}
{% set dependency19 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency20 =  ref('model_54')  %}
{% set dependency21 =  ref('model_13')  %}
{% set dependency22 =  ref('model_50')  %}
{% set dependency23 =  ref('model_68')  %}
{% set dependency24 =  ref('model_63')  %}
{% set dependency25 =  ref('model_44')  %}
{% set dependency26 =  ref('model_40')  %}
{% set dependency27 =  ref('model_83')  %}
{% set dependency28 =  ref('model_10')  %}
{% set dependency29 =  ref('model_79')  %}
{% set dependency30 =  ref('model_20')  %}
{% set dependency31 =  ref('model_66')  %}
{% set dependency32 =  ref('model_28')  %}
{% set dependency33 =  ref('model_56')  %}
{% set dependency34 =  ref('model_76')  %}
{% set dependency35 =  ref('model_22')  %}
{% set dependency36 =  ref('model_43')  %}
{% set dependency37 =  ref('model_53')  %}
{% set dependency38 =  ref('model_11')  %}
{% set dependency39 =  ref('model_88')  %}
{% set dependency40 =  ref('model_9')  %}

SELECT * from dependency0
