{% set dependency0 =  ref('model_58')  %}
{% set dependency1 =  ref('model_72')  %}
{% set dependency2 =  ref('model_73')  %}
{% set dependency3 =  ref('model_20')  %}
{% set dependency4 =  ref('model_78')  %}
{% set dependency5 =  ref('model_17')  %}
{% set dependency6 =  ref('model_76')  %}
{% set dependency7 =  ref('model_31')  %}
{% set dependency8 =  ref('model_30')  %}
{% set dependency9 =  ref('model_40')  %}
{% set dependency10 =  ref('model_39')  %}
{% set dependency11 =  ref('model_37')  %}
{% set dependency12 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency13 =  ref('model_50')  %}
{% set dependency14 =  ref('model_67')  %}
{% set dependency15 =  ref('model_51')  %}
{% set dependency16 =  ref('model_32')  %}
{% set dependency17 =  ref('model_49')  %}
{% set dependency18 =  ref('model_35')  %}
{% set dependency19 =  ref('model_70')  %}
{% set dependency20 =  ref('model_38')  %}
{% set dependency21 =  ref('model_46')  %}
{% set dependency22 =  ref('model_55')  %}
{% set dependency23 =  ref('model_23')  %}
{% set dependency24 =  ref('model_77')  %}
{% set dependency25 =  ref('model_66')  %}
{% set dependency26 =  ref('model_14')  %}
{% set dependency27 =  ref('model_26')  %}
{% set dependency28 =  ref('model_34')  %}
{% set dependency29 =  ref('model_68')  %}
{% set dependency30 =  ref('model_16')  %}
{% set dependency31 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency32 =  ref('model_4')  %}
{% set dependency33 =  ref('model_53')  %}
{% set dependency34 =  ref('model_48')  %}
{% set dependency35 =  ref('model_21')  %}
{% set dependency36 =  ref('model_3')  %}
{% set dependency37 =  ref('model_43')  %}
{% set dependency38 =  ref('model_71')  %}

SELECT * from dependency0
