{% set dependency0 =  source('aayan_test', 'example_table_2')  %}
{% set dependency1 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency2 =  ref('model_3')  %}
{% set dependency3 =  ref('model_47')  %}
{% set dependency4 =  ref('model_56')  %}
{% set dependency5 =  ref('model_28')  %}
{% set dependency6 =  ref('model_34')  %}
{% set dependency7 =  ref('model_50')  %}
{% set dependency8 =  ref('model_26')  %}
{% set dependency9 =  ref('model_37')  %}
{% set dependency10 =  ref('model_41')  %}
{% set dependency11 =  ref('model_8')  %}
{% set dependency12 =  ref('model_24')  %}
{% set dependency13 =  ref('model_44')  %}
{% set dependency14 =  ref('model_12')  %}
{% set dependency15 =  ref('model_46')  %}
{% set dependency16 =  ref('model_45')  %}
{% set dependency17 =  ref('model_19')  %}
{% set dependency18 =  ref('model_31')  %}
{% set dependency19 =  ref('model_52')  %}
{% set dependency20 =  ref('model_48')  %}
{% set dependency21 =  ref('model_23')  %}
{% set dependency22 =  ref('model_15')  %}
{% set dependency23 =  ref('model_51')  %}
{% set dependency24 =  ref('model_2')  %}
{% set dependency25 =  source('aayan_test', 'example_table')  %}
{% set dependency26 =  ref('model_30')  %}
{% set dependency27 =  ref('model_7')  %}
{% set dependency28 =  ref('model_55')  %}
{% set dependency29 =  ref('model_42')  %}
{% set dependency30 =  ref('model_17')  %}
{% set dependency31 =  ref('model_39')  %}
{% set dependency32 =  ref('model_20')  %}
{% set dependency33 =  ref('model_27')  %}
{% set dependency34 =  ref('model_22')  %}
{% set dependency35 =  ref('model_18')  %}
{% set dependency36 =  ref('model_29')  %}
{% set dependency37 =  ref('model_6')  %}
{% set dependency38 =  ref('model_25')  %}
{% set dependency39 =  ref('model_10')  %}
{% set dependency40 =  ref('model_35')  %}
{% set dependency41 =  ref('model_21')  %}
{% set dependency42 =  ref('model_53')  %}
{% set dependency43 =  ref('model_14')  %}
{% set dependency44 =  ref('model_32')  %}
{% set dependency45 =  ref('model_16')  %}
{% set dependency46 =  ref('model_36')  %}
{% set dependency47 =  ref('model_4')  %}
{% set dependency48 =  ref('model_49')  %}
{% set dependency49 =  ref('model_38')  %}
{% set dependency50 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency51 =  ref('model_5')  %}
{% set dependency52 =  ref('model_9')  %}
{% set dependency53 =  ref('model_33')  %}
{% set dependency54 =  ref('model_54')  %}
{% set dependency55 =  ref('model_40')  %}

SELECT * from dependency0
