{% set dependency0 =  ref('model_15')  %}
{% set dependency1 =  ref('model_53')  %}
{% set dependency2 =  ref('model_32')  %}
{% set dependency3 =  ref('model_60')  %}
{% set dependency4 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency5 =  ref('model_50')  %}
{% set dependency6 =  ref('model_26')  %}
{% set dependency7 =  ref('model_17')  %}
{% set dependency8 =  ref('model_44')  %}
{% set dependency9 =  source('aayan_test', 'example_table_2')  %}
{% set dependency10 =  ref('model_29')  %}
{% set dependency11 =  ref('model_48')  %}
{% set dependency12 =  ref('model_6')  %}
{% set dependency13 =  ref('model_1')  %}
{% set dependency14 =  ref('model_24')  %}
{% set dependency15 =  ref('model_67')  %}
{% set dependency16 =  ref('model_2')  %}
{% set dependency17 =  ref('model_62')  %}
{% set dependency18 =  ref('model_35')  %}
{% set dependency19 =  ref('model_13')  %}
{% set dependency20 =  source('aayan_test', 'example_table')  %}
{% set dependency21 =  ref('model_54')  %}
{% set dependency22 =  ref('model_56')  %}
{% set dependency23 =  ref('model_52')  %}
{% set dependency24 =  ref('model_49')  %}
{% set dependency25 =  ref('model_18')  %}
{% set dependency26 =  ref('model_4')  %}
{% set dependency27 =  ref('model_51')  %}
{% set dependency28 =  ref('model_45')  %}
{% set dependency29 =  ref('model_19')  %}
{% set dependency30 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency31 =  ref('model_57')  %}
{% set dependency32 =  ref('model_5')  %}
{% set dependency33 =  ref('model_38')  %}
{% set dependency34 =  ref('model_12')  %}
{% set dependency35 =  ref('model_64')  %}
{% set dependency36 =  ref('model_11')  %}
{% set dependency37 =  ref('model_58')  %}
{% set dependency38 =  ref('model_43')  %}
{% set dependency39 =  ref('model_8')  %}
{% set dependency40 =  ref('model_59')  %}

SELECT * from dependency0
