{% set dependency0 =  ref('model_64')  %}
{% set dependency1 =  ref('model_59')  %}
{% set dependency2 =  ref('model_75')  %}
{% set dependency3 =  ref('model_42')  %}
{% set dependency4 =  ref('model_21')  %}
{% set dependency5 =  ref('model_34')  %}
{% set dependency6 =  ref('model_31')  %}
{% set dependency7 =  ref('model_16')  %}
{% set dependency8 =  ref('model_95')  %}
{% set dependency9 =  ref('model_4')  %}
{% set dependency10 =  ref('model_12')  %}
{% set dependency11 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency12 =  ref('model_35')  %}
{% set dependency13 =  ref('model_38')  %}
{% set dependency14 =  ref('model_17')  %}
{% set dependency15 =  ref('model_40')  %}
{% set dependency16 =  ref('model_69')  %}
{% set dependency17 =  ref('model_50')  %}
{% set dependency18 =  ref('model_45')  %}
{% set dependency19 =  source('aayan_test', 'example_table_2')  %}
{% set dependency20 =  source('aayan_test', 'example_table')  %}
{% set dependency21 =  ref('model_93')  %}
{% set dependency22 =  ref('model_58')  %}
{% set dependency23 =  ref('model_24')  %}
{% set dependency24 =  ref('model_30')  %}
{% set dependency25 =  ref('model_89')  %}
{% set dependency26 =  ref('model_66')  %}
{% set dependency27 =  ref('model_74')  %}
{% set dependency28 =  ref('model_73')  %}
{% set dependency29 =  ref('model_10')  %}
{% set dependency30 =  ref('model_56')  %}
{% set dependency31 =  ref('model_85')  %}
{% set dependency32 =  ref('model_91')  %}
{% set dependency33 =  ref('model_18')  %}
{% set dependency34 =  ref('model_61')  %}
{% set dependency35 =  ref('model_92')  %}
{% set dependency36 =  ref('model_43')  %}
{% set dependency37 =  ref('model_78')  %}

SELECT * from dependency0
