{% set dependency0 =  ref('model_5')  %}
{% set dependency1 =  ref('model_13')  %}
{% set dependency2 =  ref('model_22')  %}
{% set dependency3 =  ref('model_58')  %}
{% set dependency4 =  ref('model_31')  %}
{% set dependency5 =  source('aayan_test', 'example_table')  %}
{% set dependency6 =  ref('model_9')  %}
{% set dependency7 =  ref('model_42')  %}
{% set dependency8 =  ref('model_71')  %}
{% set dependency9 =  ref('model_62')  %}
{% set dependency10 =  ref('model_4')  %}
{% set dependency11 =  ref('model_60')  %}
{% set dependency12 =  ref('model_65')  %}
{% set dependency13 =  ref('model_38')  %}
{% set dependency14 =  ref('model_32')  %}
{% set dependency15 =  ref('model_56')  %}
{% set dependency16 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency17 =  ref('model_30')  %}
{% set dependency18 =  ref('model_44')  %}
{% set dependency19 =  ref('model_47')  %}
{% set dependency20 =  ref('model_68')  %}
{% set dependency21 =  ref('model_6')  %}
{% set dependency22 =  ref('model_67')  %}
{% set dependency23 =  ref('model_52')  %}
{% set dependency24 =  ref('model_21')  %}
{% set dependency25 =  ref('model_23')  %}
{% set dependency26 =  ref('model_72')  %}
{% set dependency27 =  ref('model_24')  %}
{% set dependency28 =  ref('model_46')  %}
{% set dependency29 =  ref('model_48')  %}
{% set dependency30 =  ref('model_16')  %}
{% set dependency31 =  ref('model_66')  %}
{% set dependency32 =  ref('model_20')  %}
{% set dependency33 =  ref('model_43')  %}
{% set dependency34 =  ref('model_45')  %}
{% set dependency35 =  ref('model_63')  %}
{% set dependency36 =  ref('model_50')  %}
{% set dependency37 =  ref('model_49')  %}
{% set dependency38 =  ref('model_64')  %}

SELECT * from dependency0
