{% set dependency0 =  ref('model_70')  %}
{% set dependency1 =  ref('model_59')  %}
{% set dependency2 =  ref('model_37')  %}
{% set dependency3 =  ref('model_28')  %}
{% set dependency4 =  ref('model_64')  %}
{% set dependency5 =  ref('model_19')  %}
{% set dependency6 =  ref('model_45')  %}
{% set dependency7 =  ref('model_13')  %}
{% set dependency8 =  ref('model_21')  %}
{% set dependency9 =  ref('model_71')  %}
{% set dependency10 =  ref('model_72')  %}
{% set dependency11 =  source('aayan_test', 'example_table')  %}
{% set dependency12 =  ref('model_6')  %}
{% set dependency13 =  ref('model_47')  %}
{% set dependency14 =  ref('model_10')  %}
{% set dependency15 =  ref('model_76')  %}
{% set dependency16 =  ref('model_20')  %}
{% set dependency17 =  ref('model_53')  %}
{% set dependency18 =  ref('model_33')  %}
{% set dependency19 =  ref('model_46')  %}
{% set dependency20 =  ref('model_67')  %}
{% set dependency21 =  ref('model_51')  %}
{% set dependency22 =  ref('model_65')  %}
{% set dependency23 =  ref('model_16')  %}
{% set dependency24 =  ref('model_75')  %}
{% set dependency25 =  ref('model_56')  %}
{% set dependency26 =  ref('model_66')  %}
{% set dependency27 =  ref('model_52')  %}
{% set dependency28 =  ref('model_24')  %}
{% set dependency29 =  ref('model_44')  %}
{% set dependency30 =  ref('model_69')  %}

SELECT * from dependency0
