{% set dependency0 =  ref('model_72')  %}
{% set dependency1 =  ref('model_46')  %}
{% set dependency2 =  ref('model_53')  %}
{% set dependency3 =  ref('model_16')  %}
{% set dependency4 =  ref('model_85')  %}
{% set dependency5 =  ref('model_11')  %}
{% set dependency6 =  ref('model_42')  %}
{% set dependency7 =  ref('model_9')  %}
{% set dependency8 =  ref('model_52')  %}
{% set dependency9 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency10 =  ref('model_93')  %}
{% set dependency11 =  ref('model_88')  %}
{% set dependency12 =  ref('model_81')  %}
{% set dependency13 =  ref('model_59')  %}
{% set dependency14 =  ref('model_47')  %}
{% set dependency15 =  ref('model_31')  %}
{% set dependency16 =  ref('model_57')  %}
{% set dependency17 =  ref('model_10')  %}
{% set dependency18 =  ref('model_67')  %}
{% set dependency19 =  ref('model_17')  %}
{% set dependency20 =  ref('model_63')  %}
{% set dependency21 =  ref('model_18')  %}
{% set dependency22 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency23 =  ref('model_19')  %}
{% set dependency24 =  ref('model_28')  %}
{% set dependency25 =  source('aayan_test', 'example_table_2')  %}
{% set dependency26 =  ref('model_48')  %}
{% set dependency27 =  ref('model_2')  %}
{% set dependency28 =  ref('model_45')  %}
{% set dependency29 =  ref('model_37')  %}
{% set dependency30 =  ref('model_78')  %}
{% set dependency31 =  ref('model_13')  %}
{% set dependency32 =  ref('model_38')  %}
{% set dependency33 =  ref('model_26')  %}
{% set dependency34 =  ref('model_39')  %}
{% set dependency35 =  ref('model_83')  %}
{% set dependency36 =  ref('model_66')  %}
{% set dependency37 =  ref('model_22')  %}
{% set dependency38 =  ref('model_51')  %}
{% set dependency39 =  ref('model_68')  %}
{% set dependency40 =  ref('model_79')  %}
{% set dependency41 =  ref('model_69')  %}
{% set dependency42 =  ref('model_76')  %}
{% set dependency43 =  ref('model_24')  %}
{% set dependency44 =  ref('model_35')  %}
{% set dependency45 =  ref('model_21')  %}
{% set dependency46 =  ref('model_30')  %}
{% set dependency47 =  ref('model_61')  %}
{% set dependency48 =  ref('model_73')  %}
{% set dependency49 =  ref('model_7')  %}
{% set dependency50 =  ref('model_86')  %}
{% set dependency51 =  ref('model_27')  %}
{% set dependency52 =  ref('model_33')  %}
{% set dependency53 =  ref('model_94')  %}
{% set dependency54 =  ref('model_36')  %}

SELECT * from dependency0
