{% set dependency0 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency1 =  ref('model_35')  %}
{% set dependency2 =  ref('model_83')  %}
{% set dependency3 =  ref('model_91')  %}
{% set dependency4 =  ref('model_4')  %}
{% set dependency5 =  ref('model_16')  %}
{% set dependency6 =  ref('model_21')  %}
{% set dependency7 =  source('aayan_test', 'example_table')  %}
{% set dependency8 =  ref('model_66')  %}
{% set dependency9 =  ref('model_8')  %}
{% set dependency10 =  ref('model_41')  %}
{% set dependency11 =  ref('model_58')  %}
{% set dependency12 =  ref('model_55')  %}
{% set dependency13 =  ref('model_22')  %}
{% set dependency14 =  ref('model_38')  %}
{% set dependency15 =  ref('model_23')  %}
{% set dependency16 =  ref('model_60')  %}
{% set dependency17 =  ref('model_77')  %}
{% set dependency18 =  ref('model_88')  %}
{% set dependency19 =  ref('model_92')  %}
{% set dependency20 =  ref('model_24')  %}
{% set dependency21 =  ref('model_13')  %}
{% set dependency22 =  ref('model_27')  %}
{% set dependency23 =  ref('model_76')  %}
{% set dependency24 =  ref('model_18')  %}
{% set dependency25 =  ref('model_63')  %}
{% set dependency26 =  ref('model_37')  %}
{% set dependency27 =  ref('model_48')  %}
{% set dependency28 =  ref('model_52')  %}
{% set dependency29 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency30 =  ref('model_54')  %}
{% set dependency31 =  ref('model_1')  %}
{% set dependency32 =  ref('model_67')  %}
{% set dependency33 =  ref('model_75')  %}
{% set dependency34 =  ref('model_6')  %}
{% set dependency35 =  ref('model_9')  %}
{% set dependency36 =  ref('model_45')  %}
{% set dependency37 =  ref('model_46')  %}
{% set dependency38 =  ref('model_29')  %}
{% set dependency39 =  ref('model_90')  %}
{% set dependency40 =  ref('model_79')  %}
{% set dependency41 =  source('aayan_test', 'example_table_2')  %}
{% set dependency42 =  ref('model_86')  %}
{% set dependency43 =  ref('model_32')  %}
{% set dependency44 =  ref('model_39')  %}

SELECT * from {{ dependency0 }}
