{% set dependency0 =  ref('model_58')  %}
{% set dependency1 =  ref('model_41')  %}
{% set dependency2 =  ref('model_94')  %}
{% set dependency3 =  ref('model_25')  %}
{% set dependency4 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency5 =  ref('model_22')  %}
{% set dependency6 =  ref('model_4')  %}
{% set dependency7 =  ref('model_96')  %}
{% set dependency8 =  ref('model_66')  %}
{% set dependency9 =  ref('model_68')  %}
{% set dependency10 =  ref('model_76')  %}
{% set dependency11 =  ref('model_55')  %}
{% set dependency12 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency13 =  ref('model_74')  %}
{% set dependency14 =  ref('model_34')  %}
{% set dependency15 =  ref('model_9')  %}
{% set dependency16 =  ref('model_77')  %}
{% set dependency17 =  ref('model_45')  %}
{% set dependency18 =  ref('model_79')  %}
{% set dependency19 =  ref('model_64')  %}
{% set dependency20 =  ref('model_87')  %}
{% set dependency21 =  ref('model_17')  %}
{% set dependency22 =  ref('model_20')  %}
{% set dependency23 =  source('aayan_test', 'example_table')  %}
{% set dependency24 =  ref('model_44')  %}
{% set dependency25 =  ref('model_21')  %}
{% set dependency26 =  ref('model_89')  %}
{% set dependency27 =  ref('model_82')  %}
{% set dependency28 =  ref('model_62')  %}
{% set dependency29 =  ref('model_73')  %}
{% set dependency30 =  ref('model_47')  %}
{% set dependency31 =  ref('model_95')  %}
{% set dependency32 =  ref('model_56')  %}
{% set dependency33 =  ref('model_63')  %}
{% set dependency34 =  ref('model_71')  %}
{% set dependency35 =  ref('model_65')  %}
{% set dependency36 =  ref('model_24')  %}
{% set dependency37 =  ref('model_14')  %}
{% set dependency38 =  ref('model_75')  %}

SELECT * from {{ dependency0 }}
