{% set dependency0 =  ref('model_21')  %}
{% set dependency1 =  ref('model_25')  %}
{% set dependency2 =  ref('model_37')  %}
{% set dependency3 =  ref('model_6')  %}
{% set dependency4 =  ref('model_23')  %}
{% set dependency5 =  ref('model_2')  %}
{% set dependency6 =  ref('model_14')  %}
{% set dependency7 =  ref('model_41')  %}
{% set dependency8 =  ref('model_26')  %}
{% set dependency9 =  ref('model_33')  %}
{% set dependency10 =  ref('model_10')  %}
{% set dependency11 =  ref('model_43')  %}
{% set dependency12 =  ref('model_11')  %}
{% set dependency13 =  ref('model_62')  %}
{% set dependency14 =  ref('model_5')  %}
{% set dependency15 =  source('aayan_test', 'example_table_2')  %}
{% set dependency16 =  ref('model_4')  %}
{% set dependency17 =  ref('model_54')  %}
{% set dependency18 =  ref('model_7')  %}
{% set dependency19 =  ref('model_29')  %}
{% set dependency20 =  ref('model_31')  %}
{% set dependency21 =  ref('model_35')  %}
{% set dependency22 =  ref('model_12')  %}
{% set dependency23 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency24 =  ref('model_59')  %}
{% set dependency25 =  ref('model_57')  %}
{% set dependency26 =  ref('model_36')  %}
{% set dependency27 =  source('aayan_test', 'example_table')  %}
{% set dependency28 =  ref('model_16')  %}
{% set dependency29 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency30 =  ref('model_44')  %}
{% set dependency31 =  ref('model_55')  %}
{% set dependency32 =  ref('model_50')  %}
{% set dependency33 =  ref('model_61')  %}
{% set dependency34 =  ref('model_51')  %}
{% set dependency35 =  ref('model_38')  %}
{% set dependency36 =  ref('model_53')  %}
{% set dependency37 =  ref('model_40')  %}
{% set dependency38 =  ref('model_32')  %}
{% set dependency39 =  ref('model_27')  %}
{% set dependency40 =  ref('model_49')  %}
{% set dependency41 =  ref('model_52')  %}

SELECT * from dependency0
