{% set dependency0 =  ref('model_33')  %}
{% set dependency1 =  ref('model_43')  %}
{% set dependency2 =  ref('model_53')  %}
{% set dependency3 =  ref('model_9')  %}
{% set dependency4 =  ref('model_45')  %}
{% set dependency5 =  ref('model_15')  %}
{% set dependency6 =  ref('model_10')  %}
{% set dependency7 =  ref('model_31')  %}
{% set dependency8 =  ref('model_17')  %}
{% set dependency9 =  ref('model_55')  %}
{% set dependency10 =  ref('model_19')  %}
{% set dependency11 =  ref('model_41')  %}
{% set dependency12 =  ref('model_42')  %}
{% set dependency13 =  ref('model_34')  %}
{% set dependency14 =  ref('model_30')  %}
{% set dependency15 =  source('aayan_test', 'example_table')  %}
{% set dependency16 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency17 =  ref('model_20')  %}
{% set dependency18 =  ref('model_52')  %}
{% set dependency19 =  source('aayan_test', 'example_table_2')  %}
{% set dependency20 =  ref('model_50')  %}
{% set dependency21 =  ref('model_48')  %}
{% set dependency22 =  ref('model_40')  %}
{% set dependency23 =  ref('model_12')  %}
{% set dependency24 =  ref('model_13')  %}
{% set dependency25 =  ref('model_54')  %}
{% set dependency26 =  ref('model_1')  %}
{% set dependency27 =  ref('model_46')  %}
{% set dependency28 =  ref('model_22')  %}
{% set dependency29 =  ref('model_56')  %}
{% set dependency30 =  ref('model_11')  %}
{% set dependency31 =  ref('model_44')  %}
{% set dependency32 =  ref('model_8')  %}
{% set dependency33 =  ref('model_5')  %}
{% set dependency34 =  ref('model_51')  %}
{% set dependency35 =  ref('model_24')  %}
{% set dependency36 =  ref('model_26')  %}
{% set dependency37 =  ref('model_21')  %}
{% set dependency38 =  ref('model_7')  %}
{% set dependency39 =  ref('model_47')  %}
{% set dependency40 =  ref('model_27')  %}
{% set dependency41 =  ref('model_32')  %}

SELECT * from dependency0
