{% set dependency0 =  ref('model_86')  %}
{% set dependency1 =  ref('model_88')  %}
{% set dependency2 =  ref('model_22')  %}
{% set dependency3 =  ref('model_32')  %}
{% set dependency4 =  ref('model_63')  %}
{% set dependency5 =  ref('model_93')  %}
{% set dependency6 =  ref('model_33')  %}
{% set dependency7 =  ref('model_4')  %}
{% set dependency8 =  ref('model_68')  %}
{% set dependency9 =  source('aayan_test', 'example_table_2')  %}
{% set dependency10 =  ref('model_51')  %}
{% set dependency11 =  ref('model_56')  %}
{% set dependency12 =  ref('model_2')  %}
{% set dependency13 =  ref('model_90')  %}
{% set dependency14 =  ref('model_37')  %}
{% set dependency15 =  ref('model_81')  %}
{% set dependency16 =  ref('model_45')  %}
{% set dependency17 =  ref('model_49')  %}
{% set dependency18 =  ref('model_28')  %}
{% set dependency19 =  ref('model_40')  %}
{% set dependency20 =  ref('model_83')  %}
{% set dependency21 =  ref('model_64')  %}
{% set dependency22 =  ref('model_69')  %}
{% set dependency23 =  ref('model_84')  %}
{% set dependency24 =  ref('model_35')  %}
{% set dependency25 =  ref('model_15')  %}
{% set dependency26 =  ref('model_20')  %}
{% set dependency27 =  ref('model_34')  %}
{% set dependency28 =  ref('model_29')  %}
{% set dependency29 =  ref('model_71')  %}
{% set dependency30 =  ref('model_38')  %}
{% set dependency31 =  ref('model_74')  %}
{% set dependency32 =  ref('model_87')  %}
{% set dependency33 =  ref('model_89')  %}
{% set dependency34 =  ref('model_14')  %}
{% set dependency35 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency36 =  ref('model_50')  %}
{% set dependency37 =  ref('model_78')  %}
{% set dependency38 =  ref('model_11')  %}
{% set dependency39 =  ref('model_76')  %}
{% set dependency40 =  ref('model_18')  %}
{% set dependency41 =  ref('model_75')  %}
{% set dependency42 =  ref('model_21')  %}
{% set dependency43 =  ref('model_31')  %}
{% set dependency44 =  ref('model_25')  %}
{% set dependency45 =  ref('model_60')  %}
{% set dependency46 =  ref('model_85')  %}
{% set dependency47 =  ref('model_65')  %}
{% set dependency48 =  source('aayan_test', 'example_table')  %}
{% set dependency49 =  ref('model_12')  %}
{% set dependency50 =  ref('model_42')  %}
{% set dependency51 =  ref('model_53')  %}
{% set dependency52 =  ref('model_54')  %}
{% set dependency53 =  ref('model_94')  %}
{% set dependency54 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency55 =  ref('model_36')  %}

SELECT * from dependency0
