{% set dependency0 =  ref('model_27')  %}
{% set dependency1 =  ref('model_59')  %}
{% set dependency2 =  ref('model_4')  %}
{% set dependency3 =  ref('model_53')  %}
{% set dependency4 =  ref('model_39')  %}
{% set dependency5 =  ref('model_66')  %}
{% set dependency6 =  ref('model_29')  %}
{% set dependency7 =  ref('model_23')  %}
{% set dependency8 =  ref('model_56')  %}
{% set dependency9 =  ref('model_37')  %}
{% set dependency10 =  ref('model_21')  %}
{% set dependency11 =  ref('model_17')  %}
{% set dependency12 =  ref('model_9')  %}
{% set dependency13 =  ref('model_40')  %}
{% set dependency14 =  ref('model_48')  %}
{% set dependency15 =  ref('model_52')  %}
{% set dependency16 =  ref('model_42')  %}
{% set dependency17 =  ref('model_44')  %}
{% set dependency18 =  ref('model_24')  %}
{% set dependency19 =  source('aayan_test', 'example_table_2')  %}
{% set dependency20 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency21 =  ref('model_54')  %}
{% set dependency22 =  ref('model_26')  %}
{% set dependency23 =  ref('model_58')  %}
{% set dependency24 =  ref('model_51')  %}
{% set dependency25 =  ref('model_67')  %}
{% set dependency26 =  ref('model_7')  %}

SELECT * from dependency0
