{% set dependency0 =  ref('model_64')  %}
{% set dependency1 =  ref('model_5')  %}
{% set dependency2 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency3 =  ref('model_35')  %}
{% set dependency4 =  source('aayan_test', 'example_table')  %}
{% set dependency5 =  ref('model_27')  %}
{% set dependency6 =  ref('model_14')  %}
{% set dependency7 =  source('aayan_test', 'example_table_2')  %}
{% set dependency8 =  ref('model_74')  %}
{% set dependency9 =  ref('model_21')  %}
{% set dependency10 =  ref('model_42')  %}
{% set dependency11 =  ref('model_9')  %}
{% set dependency12 =  ref('model_28')  %}
{% set dependency13 =  ref('model_60')  %}
{% set dependency14 =  ref('model_36')  %}
{% set dependency15 =  ref('model_59')  %}
{% set dependency16 =  ref('model_63')  %}
{% set dependency17 =  ref('model_68')  %}
{% set dependency18 =  ref('model_50')  %}
{% set dependency19 =  ref('model_45')  %}
{% set dependency20 =  ref('model_15')  %}
{% set dependency21 =  ref('model_13')  %}
{% set dependency22 =  ref('model_19')  %}
{% set dependency23 =  ref('model_72')  %}
{% set dependency24 =  ref('model_66')  %}
{% set dependency25 =  ref('model_57')  %}
{% set dependency26 =  ref('model_40')  %}
{% set dependency27 =  ref('model_6')  %}
{% set dependency28 =  ref('model_39')  %}
{% set dependency29 =  ref('model_69')  %}
{% set dependency30 =  ref('model_56')  %}

SELECT * from dependency0
