{% set dependency0 =  ref('model_41')  %}
{% set dependency1 =  ref('model_84')  %}
{% set dependency2 =  ref('model_90')  %}
{% set dependency3 =  ref('model_70')  %}
{% set dependency4 =  ref('model_98')  %}
{% set dependency5 =  ref('model_45')  %}
{% set dependency6 =  ref('model_92')  %}
{% set dependency7 =  ref('model_8')  %}
{% set dependency8 =  ref('model_24')  %}
{% set dependency9 =  ref('model_42')  %}
{% set dependency10 =  ref('model_62')  %}
{% set dependency11 =  ref('model_33')  %}
{% set dependency12 =  ref('model_46')  %}
{% set dependency13 =  ref('model_36')  %}
{% set dependency14 =  ref('model_7')  %}
{% set dependency15 =  ref('model_83')  %}
{% set dependency16 =  ref('model_34')  %}
{% set dependency17 =  ref('model_44')  %}
{% set dependency18 =  ref('model_6')  %}
{% set dependency19 =  ref('model_38')  %}
{% set dependency20 =  ref('model_93')  %}
{% set dependency21 =  ref('model_61')  %}
{% set dependency22 =  ref('model_25')  %}
{% set dependency23 =  ref('model_76')  %}
{% set dependency24 =  ref('model_40')  %}
{% set dependency25 =  ref('model_31')  %}
{% set dependency26 =  ref('model_49')  %}
{% set dependency27 =  ref('model_17')  %}
{% set dependency28 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency29 =  ref('model_63')  %}
{% set dependency30 =  ref('model_30')  %}
{% set dependency31 =  ref('model_9')  %}
{% set dependency32 =  ref('model_16')  %}
{% set dependency33 =  ref('model_11')  %}
{% set dependency34 =  ref('model_53')  %}
{% set dependency35 =  ref('model_79')  %}
{% set dependency36 =  ref('model_18')  %}
{% set dependency37 =  ref('model_23')  %}
{% set dependency38 =  source('aayan_test', 'example_table_2')  %}
{% set dependency39 =  ref('model_13')  %}
{% set dependency40 =  ref('model_43')  %}
{% set dependency41 =  ref('model_82')  %}
{% set dependency42 =  ref('model_26')  %}
{% set dependency43 =  ref('model_27')  %}

SELECT * from dependency0
