{% set dependency0 =  ref('model_51')  %}
{% set dependency1 =  ref('model_53')  %}
{% set dependency2 =  ref('model_3')  %}
{% set dependency3 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency4 =  ref('model_40')  %}
{% set dependency5 =  ref('model_23')  %}
{% set dependency6 =  ref('model_39')  %}
{% set dependency7 =  ref('model_27')  %}
{% set dependency8 =  ref('model_5')  %}
{% set dependency9 =  ref('model_56')  %}
{% set dependency10 =  ref('model_58')  %}
{% set dependency11 =  ref('model_41')  %}
{% set dependency12 =  ref('model_52')  %}
{% set dependency13 =  ref('model_10')  %}
{% set dependency14 =  ref('model_28')  %}
{% set dependency15 =  ref('model_25')  %}
{% set dependency16 =  ref('model_34')  %}
{% set dependency17 =  ref('model_42')  %}
{% set dependency18 =  ref('model_32')  %}
{% set dependency19 =  ref('model_19')  %}
{% set dependency20 =  ref('model_1')  %}
{% set dependency21 =  ref('model_37')  %}
{% set dependency22 =  ref('model_57')  %}
{% set dependency23 =  ref('model_45')  %}
{% set dependency24 =  ref('model_15')  %}
{% set dependency25 =  ref('model_13')  %}
{% set dependency26 =  ref('model_33')  %}
{% set dependency27 =  ref('model_29')  %}
{% set dependency28 =  ref('model_7')  %}
{% set dependency29 =  ref('model_55')  %}
{% set dependency30 =  ref('model_11')  %}
{% set dependency31 =  ref('model_9')  %}
{% set dependency32 =  ref('model_44')  %}
{% set dependency33 =  source('aayan_test', 'example_table_2')  %}
{% set dependency34 =  ref('model_35')  %}
{% set dependency35 =  ref('model_14')  %}
{% set dependency36 =  ref('model_21')  %}

SELECT * from dependency0
