{% set dependency0 =  ref('model_9')  %}
{% set dependency1 =  ref('model_65')  %}
{% set dependency2 =  ref('model_33')  %}
{% set dependency3 =  ref('model_66')  %}
{% set dependency4 =  ref('model_72')  %}
{% set dependency5 =  ref('model_46')  %}
{% set dependency6 =  ref('model_1')  %}
{% set dependency7 =  ref('model_19')  %}
{% set dependency8 =  ref('model_27')  %}
{% set dependency9 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency10 =  ref('model_56')  %}
{% set dependency11 =  ref('model_24')  %}
{% set dependency12 =  ref('model_76')  %}
{% set dependency13 =  ref('model_48')  %}
{% set dependency14 =  ref('model_42')  %}
{% set dependency15 =  ref('model_38')  %}
{% set dependency16 =  ref('model_28')  %}
{% set dependency17 =  ref('model_59')  %}
{% set dependency18 =  ref('model_39')  %}
{% set dependency19 =  ref('model_52')  %}
{% set dependency20 =  ref('model_16')  %}
{% set dependency21 =  source('aayan_test', 'example_table_2')  %}
{% set dependency22 =  ref('model_20')  %}
{% set dependency23 =  ref('model_51')  %}
{% set dependency24 =  ref('model_79')  %}
{% set dependency25 =  ref('model_49')  %}
{% set dependency26 =  ref('model_14')  %}
{% set dependency27 =  ref('model_55')  %}
{% set dependency28 =  ref('model_34')  %}
{% set dependency29 =  ref('model_12')  %}
{% set dependency30 =  ref('model_78')  %}
{% set dependency31 =  ref('model_75')  %}
{% set dependency32 =  ref('model_11')  %}
{% set dependency33 =  ref('model_10')  %}

SELECT * from dependency0
