{% set dependency0 =  ref('model_20')  %}
{% set dependency1 =  ref('model_23')  %}
{% set dependency2 =  ref('model_43')  %}
{% set dependency3 =  ref('model_28')  %}
{% set dependency4 =  ref('model_14')  %}
{% set dependency5 =  ref('model_45')  %}
{% set dependency6 =  ref('model_46')  %}
{% set dependency7 =  ref('model_7')  %}
{% set dependency8 =  ref('model_53')  %}
{% set dependency9 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency10 =  source('aayan_test', 'example_table')  %}
{% set dependency11 =  ref('model_19')  %}
{% set dependency12 =  ref('model_1')  %}
{% set dependency13 =  ref('model_51')  %}
{% set dependency14 =  ref('model_39')  %}
{% set dependency15 =  ref('model_29')  %}
{% set dependency16 =  ref('model_70')  %}
{% set dependency17 =  ref('model_62')  %}
{% set dependency18 =  ref('model_68')  %}
{% set dependency19 =  ref('model_12')  %}
{% set dependency20 =  ref('model_6')  %}
{% set dependency21 =  ref('model_11')  %}
{% set dependency22 =  ref('model_8')  %}
{% set dependency23 =  ref('model_57')  %}
{% set dependency24 =  ref('model_50')  %}
{% set dependency25 =  ref('model_4')  %}
{% set dependency26 =  ref('model_59')  %}
{% set dependency27 =  ref('model_38')  %}
{% set dependency28 =  ref('model_40')  %}
{% set dependency29 =  ref('model_10')  %}
{% set dependency30 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency31 =  ref('model_41')  %}
{% set dependency32 =  ref('model_17')  %}
{% set dependency33 =  ref('model_2')  %}
{% set dependency34 =  ref('model_16')  %}
{% set dependency35 =  ref('model_60')  %}
{% set dependency36 =  ref('model_65')  %}
{% set dependency37 =  ref('model_73')  %}
{% set dependency38 =  ref('model_48')  %}
{% set dependency39 =  ref('model_3')  %}
{% set dependency40 =  ref('model_24')  %}
{% set dependency41 =  ref('model_33')  %}
{% set dependency42 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency43 =  ref('model_78')  %}
{% set dependency44 =  ref('model_34')  %}
{% set dependency45 =  ref('model_75')  %}

SELECT * from {{ dependency0 }}
