{% set dependency0 =  ref('model_54')  %}
{% set dependency1 =  ref('model_37')  %}
{% set dependency2 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency3 =  ref('model_78')  %}
{% set dependency4 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency5 =  ref('model_51')  %}
{% set dependency6 =  ref('model_75')  %}
{% set dependency7 =  ref('model_12')  %}
{% set dependency8 =  ref('model_2')  %}
{% set dependency9 =  source('aayan_test', 'example_table')  %}
{% set dependency10 =  ref('model_21')  %}
{% set dependency11 =  ref('model_61')  %}
{% set dependency12 =  ref('model_19')  %}
{% set dependency13 =  ref('model_35')  %}
{% set dependency14 =  ref('model_84')  %}
{% set dependency15 =  ref('model_82')  %}
{% set dependency16 =  ref('model_83')  %}
{% set dependency17 =  ref('model_7')  %}
{% set dependency18 =  ref('model_4')  %}
{% set dependency19 =  ref('model_25')  %}
{% set dependency20 =  ref('model_47')  %}
{% set dependency21 =  ref('model_87')  %}
{% set dependency22 =  ref('model_77')  %}
{% set dependency23 =  ref('model_28')  %}
{% set dependency24 =  ref('model_63')  %}
{% set dependency25 =  ref('model_23')  %}
{% set dependency26 =  ref('model_20')  %}
{% set dependency27 =  ref('model_49')  %}

SELECT * from {{ dependency0 }}
