{% set dependency0 =  ref('model_61')  %}
{% set dependency1 =  ref('model_46')  %}
{% set dependency2 =  ref('model_5')  %}
{% set dependency3 =  ref('model_62')  %}
{% set dependency4 =  ref('model_19')  %}
{% set dependency5 =  ref('model_32')  %}
{% set dependency6 =  ref('model_11')  %}
{% set dependency7 =  ref('model_27')  %}
{% set dependency8 =  ref('model_83')  %}
{% set dependency9 =  ref('model_52')  %}
{% set dependency10 =  ref('model_43')  %}
{% set dependency11 =  source('aayan_test', 'example_table')  %}
{% set dependency12 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency13 =  ref('model_84')  %}
{% set dependency14 =  ref('model_55')  %}
{% set dependency15 =  ref('model_33')  %}
{% set dependency16 =  ref('model_69')  %}
{% set dependency17 =  ref('model_51')  %}
{% set dependency18 =  ref('model_34')  %}
{% set dependency19 =  ref('model_41')  %}
{% set dependency20 =  ref('model_60')  %}
{% set dependency21 =  ref('model_53')  %}
{% set dependency22 =  ref('model_23')  %}
{% set dependency23 =  ref('model_39')  %}
{% set dependency24 =  ref('model_35')  %}
{% set dependency25 =  ref('model_31')  %}
{% set dependency26 =  ref('model_79')  %}
{% set dependency27 =  ref('model_3')  %}
{% set dependency28 =  ref('model_36')  %}
{% set dependency29 =  ref('model_73')  %}
{% set dependency30 =  ref('model_16')  %}
{% set dependency31 =  ref('model_7')  %}
{% set dependency32 =  ref('model_68')  %}
{% set dependency33 =  ref('model_20')  %}
{% set dependency34 =  ref('model_37')  %}
{% set dependency35 =  ref('model_13')  %}
{% set dependency36 =  ref('model_26')  %}
{% set dependency37 =  ref('model_6')  %}
{% set dependency38 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency39 =  ref('model_50')  %}
{% set dependency40 =  ref('model_17')  %}

SELECT * from dependency0
