{% set dependency0 =  ref('model_31')  %}
{% set dependency1 =  ref('model_66')  %}
{% set dependency2 =  ref('model_26')  %}
{% set dependency3 =  ref('model_33')  %}
{% set dependency4 =  ref('model_64')  %}
{% set dependency5 =  ref('model_43')  %}
{% set dependency6 =  ref('model_49')  %}
{% set dependency7 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency8 =  ref('model_57')  %}
{% set dependency9 =  ref('model_52')  %}
{% set dependency10 =  ref('model_42')  %}
{% set dependency11 =  ref('model_59')  %}
{% set dependency12 =  ref('model_71')  %}
{% set dependency13 =  ref('model_17')  %}
{% set dependency14 =  ref('model_38')  %}
{% set dependency15 =  ref('model_2')  %}
{% set dependency16 =  ref('model_48')  %}
{% set dependency17 =  source('aayan_test', 'example_table_2')  %}
{% set dependency18 =  ref('model_22')  %}
{% set dependency19 =  ref('model_24')  %}
{% set dependency20 =  ref('model_4')  %}
{% set dependency21 =  ref('model_19')  %}
{% set dependency22 =  ref('model_47')  %}
{% set dependency23 =  ref('model_40')  %}
{% set dependency24 =  ref('model_25')  %}
{% set dependency25 =  ref('model_54')  %}
{% set dependency26 =  ref('model_65')  %}
{% set dependency27 =  ref('model_62')  %}
{% set dependency28 =  ref('model_15')  %}
{% set dependency29 =  ref('model_14')  %}
{% set dependency30 =  ref('model_50')  %}
{% set dependency31 =  ref('model_9')  %}
{% set dependency32 =  ref('model_20')  %}
{% set dependency33 =  ref('model_67')  %}
{% set dependency34 =  ref('model_69')  %}
{% set dependency35 =  ref('model_11')  %}
{% set dependency36 =  ref('model_61')  %}
{% set dependency37 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency38 =  ref('model_1')  %}

SELECT * from dependency0
