{% set dependency0 =  ref('model_80')  %}
{% set dependency1 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency2 =  ref('model_53')  %}
{% set dependency3 =  ref('model_52')  %}
{% set dependency4 =  ref('model_59')  %}
{% set dependency5 =  ref('model_74')  %}
{% set dependency6 =  source('aayan_test', 'example_table_2')  %}
{% set dependency7 =  ref('model_64')  %}
{% set dependency8 =  ref('model_40')  %}
{% set dependency9 =  ref('model_22')  %}
{% set dependency10 =  ref('model_70')  %}
{% set dependency11 =  ref('model_10')  %}
{% set dependency12 =  ref('model_21')  %}
{% set dependency13 =  source('aayan_test', 'example_table')  %}
{% set dependency14 =  ref('model_8')  %}
{% set dependency15 =  ref('model_62')  %}
{% set dependency16 =  ref('model_11')  %}
{% set dependency17 =  ref('model_89')  %}
{% set dependency18 =  ref('model_87')  %}
{% set dependency19 =  ref('model_42')  %}
{% set dependency20 =  ref('model_78')  %}
{% set dependency21 =  ref('model_77')  %}
{% set dependency22 =  ref('model_76')  %}
{% set dependency23 =  ref('model_20')  %}
{% set dependency24 =  ref('model_73')  %}
{% set dependency25 =  ref('model_50')  %}
{% set dependency26 =  ref('model_2')  %}
{% set dependency27 =  ref('model_66')  %}
{% set dependency28 =  ref('model_83')  %}
{% set dependency29 =  ref('model_28')  %}
{% set dependency30 =  ref('model_71')  %}
{% set dependency31 =  source('aayan_test', 'Aayan_S3_Input')  %}
{% set dependency32 =  ref('model_7')  %}
{% set dependency33 =  ref('model_14')  %}
{% set dependency34 =  ref('model_13')  %}
{% set dependency35 =  ref('model_41')  %}
{% set dependency36 =  ref('model_67')  %}
{% set dependency37 =  ref('model_85')  %}
{% set dependency38 =  ref('model_93')  %}
{% set dependency39 =  ref('model_88')  %}
{% set dependency40 =  ref('model_3')  %}
{% set dependency41 =  ref('model_91')  %}
{% set dependency42 =  ref('model_27')  %}
{% set dependency43 =  ref('model_58')  %}

SELECT * from dependency0
