{% set dependency0 =  ref('model_8')  %}
{% set dependency1 =  ref('model_6')  %}
{% set dependency2 =  ref('model_11')  %}
{% set dependency3 =  ref('model_63')  %}
{% set dependency4 =  ref('model_3')  %}
{% set dependency5 =  ref('model_56')  %}
{% set dependency6 =  source('aayan_test', 'Aayan_S3_Lots_Of_Small_Files')  %}
{% set dependency7 =  ref('model_20')  %}
{% set dependency8 =  ref('model_49')  %}
{% set dependency9 =  ref('model_10')  %}
{% set dependency10 =  ref('model_1')  %}
{% set dependency11 =  ref('model_83')  %}
{% set dependency12 =  ref('model_67')  %}
{% set dependency13 =  ref('model_71')  %}
{% set dependency14 =  source('aayan_test', 'example_table_2')  %}
{% set dependency15 =  ref('model_51')  %}
{% set dependency16 =  ref('model_39')  %}
{% set dependency17 =  source('aayan_test', 'example_table')  %}
{% set dependency18 =  ref('model_57')  %}
{% set dependency19 =  ref('model_74')  %}
{% set dependency20 =  ref('model_24')  %}
{% set dependency21 =  ref('model_53')  %}
{% set dependency22 =  ref('model_36')  %}
{% set dependency23 =  ref('model_14')  %}
{% set dependency24 =  ref('model_50')  %}
{% set dependency25 =  ref('model_41')  %}
{% set dependency26 =  source('aayan_test', 'Aayan_S3_Even_More_Small_Files')  %}
{% set dependency27 =  ref('model_68')  %}
{% set dependency28 =  ref('model_4')  %}
{% set dependency29 =  ref('model_58')  %}
{% set dependency30 =  ref('model_44')  %}
{% set dependency31 =  ref('model_70')  %}
{% set dependency32 =  ref('model_60')  %}

SELECT * from dependency0
